f2fs_utils: fix build break in static_sdk_tools
external/f2fs-tools/mkfs/f2fs_format.c:357:
    error: undefined reference to dev_read_version
clang: error:
    linker command failed with exit code 1 (use -v to see invocation)
make: *** [out/host/linux-x86/obj/lib/libf2fs_fmt_host_dyn.so] Error 1

Change-Id: I9bf1eec9ee60aa2fc55a3d0793a67d36f271acef

Conflicts:
	f2fs_utils/f2fs_ioutils.c